### ISSUE TITLE
"package.json" Not Pushed

### ISSUE THREAD

**Issue by dr-hextanium** [CyberCDN/Simple-DJS-Template#1]
Firstly, this is my first issue, so I would like to apologize if I do something unconventionally or wrong.

Now, to the issue.
In **`README.md`** it says:
> [Step 7] Type `npm i` into your console; then once all packages are installed type `node index`.  
Running `npm i` is useless since there is no `package.json`.

Please add the package.json if you can, and DM me at Hextanium#5890 on Discord if you have any questions, or would like to correct me.
(Amazing project by the way, keep up the great work!)

**Comment by 2M4U** [comment]
Issue has been resolved, you may find the `package.json` at this location [here](https://github.com/CyberCDN/Complex-DiscordJS-Bot-Template/blob/main/package.json) 

*If you have anymore issues with this repository/issue please feel free to reopen this issue.*
